### ISSUE TITLE
Настройка и установка NGINX

### ISSUE THREAD

**Issue by prafdin** [IT-Prospects/business-calendar-configuration#7]

**Comment by nikitonya** [comment]
При переводе задачи в Ready необходимо указывать size, @Jendozzz укажи его.

**Comment by Jendozzz** [comment]
### Гайд по установке и настройке:

1. установка
`sudo apt-get update`
`sudo apt-get install nginx`

2. включение
`sudo systemctl start nginx`

3. создание директории для сайта
`sudo mkdir -p /var/www/site`

4. клонирование репозитория с github
`git clone https://github.com/IT-Prospects/business-calendar-frontend.git ~/site`

5. копирование файлов в директорию сайта
`sudo cp -rT ~/site/src /var/www/site`

6. изменение файла конфигурации nginx.conf
`sudo nano /etc/nginx/nginx.conf`

7. перезапуск nginx
`sudo systemctl restart nginx`

**Comment by prafdin** [comment]
Добавь nginx.conf в репозиторий в свою ветку и заведи PR, остальное всё ок
