### ISSUE TITLE
Создание виртуальной машины с публичным IP

### ISSUE THREAD

**Issue by nikitonya** [IT-Prospects/business-calendar-configuration#9]

**Comment by Altolele** [comment]
**Примечание**: мануал написан с расчетом на то, что используются динамические публичные адреса виртуальных машины. Поскольку в целях экономии мы отключаем виртуальные машины, то при повторном запуске ip-адрес изменится и указывать его в мануале бессмысленно.

0. Зайти в Виртуальные машины Yandex Cloud организации https://console.cloud.yandex.ru/folders/b1gciiq4bintfa7bv3b8/compute/instances

1. Включить виртуальную машину `control-vm` в яндекс облаке организации. Запомнить публичный адрес машины.

2. Включить виртуальную машину `webserver` в яндекс облаке организации. Запомнить публичный адрес машины.

3. Подключиться к виртуальной машине `control-vm` по ssh, введя в командой строке `ssh <имя пользователя>@<Публичный адрес VM>` 
Имя пользователя: использовать имя, которое назначил Женя (уточнять у него)
Публичный адрес VM: _публичный адрес машины control-vm_

4. Подключиться к виртуальной машине `webserver` по ssh, введя в консоли `ssh <имя пользователя>@<Публичный адрес VM>` 
Имя пользователя: _webserver_
Публичный адрес VM: _публичный адрес машины webserver_

5. Ввести в консоли команду `cat welcome`. Проверить отображение приветственного сообщения :)

**Comment by prafdin** [comment]
Всё ок, только дополнительно попрошу сделать две вещи.
- Чтобы зайти на машину нужно иметь доступ к логину и паролю. 
Логин/пароль можно указать в гите (при это шифруя пароль к машине мастер паролем). У этого подхода есть очевидные проблемы: пароль, хоть и в зашифрованном виде, хранится в публичном репозитории; нужно знать мастер пароль; невозможно осуществить RBAC подход. В промышленности используются специальные сервисы по управлению секретами, например, Vault. В нашем случае можем ограничится SaaS решением от yandex cloud - Lockbox. 
**Итого**: нужно настроить хранение секрета для prod стенда в lockbox.
- Зафиксировать в configuration репозитории информацию о prod стенде (айпи, id креды в lockbox). 
**Итого**: в репозиторий с конфигурацией завести PR с добавлением нужной инфы

**Comment by prafdin** [comment]
Всё ок. Любопытно что ты запускал это с локальной машины, а не с control. Но если так удобно, то ок.
